name: Deploy staging api
on: 
  workflow_dispatch:
    inputs:
      version:
        description: restart
        default: v1.0.0
        required: true

jobs:
  restart-staging-backend:
    name: Restart backend
    runs-on: ubuntu-latest

    steps:  
      - name: Perform restart
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_URL }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: ${{ secrets.REBUILD_CMD }}