name: Deploy production gateway
on:
  workflow_dispatch:

jobs:
  restart-offchain-subnames-api:
    name: Deploy production gateway
    runs-on: ubuntu-latest

    steps:
      - name: Perform restart
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_URL_PROD }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          passphrase: ${{ secrets.PASSPHASE }}
          script: |
            docker stop offchain-gateway
            docker rm offchain-gateway
            docker image pull registry.digitalocean.com/namespace/offchain-gateway-prod:latest
            docker run -d -p 80:3000 --env-file prod.env --name offchain-gateway registry.digitalocean.com/namespace/offchain-gateway-prod:latest
