name: Deploy offchain subnames api
on:
  workflow_dispatch:
    inputs:
      version:
        description: restart
        default: v1.0.0
        required: true

jobs:
  restart-offchain-subnames-api:
    name: Restart offchain subnames api
    runs-on: ubuntu-latest

    steps:
      - name: Perform restart
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_URL_PROD }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            docker stop offchain-gateway
            docker rm offchain-gateway
            docker image pull registry.digitalocean.com/namespace/offchain-gateway-prod:latest
            docker run -d -p 80:3000 --env-file prod.env --name offchain-gateway registry.digitalocean.com/namespace/offchain-gateway-prod:latest
